services:
  easy-study:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_DISABLE_REQUIRE=true